# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  catalogdb:
    image: mongo
  
  basketdb:
    image: redis:alpine

  catalogapi:
    image: catalogapi
    build:
      context: .
      dockerfile: Catalog.API/Dockerfile
  
  basket.api:
    image: basketapi
    build: 
      context: .
      dockerfile: Basket.API/Dockerfile
  
volumes:
  mongo_data: